project:
  type: website
  resources:
    - images
    - data
    - "!multiclass-portfolio-website/**"

  render:
    - "*.qmd"
    - "*.ipynb"
    - "!multiclass-portfolio-website/**"

website:
  title: "DSAN-5000: Project"
  favicon: "assets/gu-logo.png"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: report/report.qmd
        text: Report
      - text: "Technical details"
        menu: 
          - text: Data-collection
            href: technical-details/data-collection/main.ipynb 
          - text: Data-cleaning
            href: technical-details/data-cleaning/main.ipynb 
          - text: Counterfactual Data Balancing
            href: technical-details/data-balancing/main.ipynb
          - text: Exploratory Data Analysis
            href: technical-details/eda/main.ipynb 
          - text: Unsupervised Learning
            href: technical-details/unsupervised-learning/main.ipynb 
          - text: Supervised Learning
            href: technical-details/supervised-learning/main.ipynb 
          - text: Progress Log
            href: technical-details/progress-log.qmd
          - text: LLM usage Log
            href: technical-details/llm-usage-log.qmd
      - href: bibliography.qmd
        text: Bibliography
      - href: appendix.qmd
        text: Appendix
    right:
      - icon: github
        href: "https://github.com/courtneyrgreen/dsan5000_final_project"
      - text: "Back to Portfolio"
        href: "https://crg123.georgetown.domains/"

format:
  html:
    theme:
      - lux
      - styles.scss
    bibliography: assets/references.bib
    csl:  assets/apa-numeric-superscript.csl
    toc: true
    toc-depth: 3 
    page-layout: full 
    



