project:
  type: website
  resources:
    - audio
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!xtra"

website:
  title: "DSAN-5000: Project"
  favicon: "assets/gu-logo.png"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: instructions/overview.qmd
        text: Instructions
      - href: report/report.qmd
        text: Report
      - text: "Technical details"
        menu: 
          - text: Data-collection
            href: technical-details/data-collection/main.ipynb 
          - text: Data-cleaning
            href: technical-details/data-cleaning/main.ipynb 
          - text: Counterfactual Data Balancing
            href: technical-details/data-balancing/main.ipynb
          - text: Exploratory Data Analysis
            href: technical-details/eda/main.ipynb 
          - text: Unsupervised Learning
            href: technical-details/unsupervised-learning/main.ipynb 
          - text: Supervised Learning
            href: technical-details/supervised-learning/main.ipynb 
          - text: Progress Log
            href: technical-details/progress-log.qmd
          - text: LLM usage Log
            href: technical-details/llm-usage-log.qmd
    right:
      - icon: github
        href: "https://github.com/dsan-5000/project-courtneyrgreen.git"

page-footer:
    background: light # or `dark`
    left: Copyright 2024, Courtney Green

format:
  html:
    theme:
      - lux
      - styles.scss
    bibliography:   ./assets/references.bib
    csl:  ./assets/nature.csl
    toc: true
    toc-depth: 3 
    page-layout: full 
    



